" Dependencies you might want to install
" $ sudo apt-get install vim-gui-common
" $ sudo apt-get install vim-runtime

set nu                " Show line numbers
set linebreak         " Break lines at word
set showbreak=+++     " Wrap-broken line prefix
set showmatch         " Highlight matching brace
set visualbell        " Use visual bell (no beeping)
set nospell           " Enable spell-checking
set noerrorbells      " no bells in terminal

set hlsearch          " Highlight all search results
set smartcase         " Enable smart-case search
set ignorecase        " Always case-insensitive
set incsearch         " Incremental search
set wrapscan

set softtabstop=2
set tabstop=2
set shiftwidth=2
set textwidth=80      " Line wrap (number of columns)
set expandtab
set backspace=2

" this should get best indenting for most common filetypes
filetype on
filetype indent plugin on
set autoindent
set smartindent

" display
set scrolloff=5       " scroll offset, min lines above/below cursor
set scrolljump=5      " jump 5 lines when running out of the screen
set sidescroll=10     " minimum columns to scroll horizontally
set showcmd           " show command status
set showmatch         " flashes matching paren when one is typed
set showmode          " show editing mode in status (-- INSERT --)
set ruler             " show cursor position

" enable mouse scroll
set mouse=a

" Clipboard integration
set clipboard=unnamed,unnamedplus

" Performance improvements
set lazyredraw        " Don't redraw while executing macros
set ttyfast           " Faster redrawing
set updatetime=300    " Faster completion (default is 4000ms)

" Quality of life improvements
set wildmenu          " Better command-line completion
set wildmode=longest:full,full
set hidden            " Allow hidden buffers with unsaved changes
set splitbelow        " Open horizontal splits below
set splitright        " Open vertical splits to the right

" Advanced
set ruler
set undolevels=1000   " number of undos stored
set viminfo='50,"50   " '=marks for x files, "=registers for x files
" set backspace=indent,eol,start
set noautowriteall      " Auto write all changes

" Keep some stuff in the history
set history=1000

" Automatically read a file that has changed on disk
set noautoread

" Do not highlight the current line and column
set nocursorline
set nocursorcolumn

" Highlight unwanted spaces
let c_space_errors=1

" Enable 80 column line
set colorcolumn=+1
highlight ColorColumn ctermbg=white guibg=white

" Remember last position of cursor in a file
if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif

" With a map leader it's possible to do extra key combinations
" like <leader>w saves the current file
let mapleader = ";"
let g:mapleader = ";"

" Fast saving and save+close
nmap <leader>w :w<cr><cr>
nmap <leader>q :wq!<cr>

" Clear search highlighting with Esc
nnoremap <silent> <Esc><Esc> :nohlsearch<CR>

" Clear extra whitespaces on saving file buffer
autocmd BufWritePre * :%s/\s\+$//e

" Enable color syntax highlighting
syntax on

" ============================================================================
" Modern Plugin Setup using vim-plug
" ============================================================================
" To install vim-plug, run:
" curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
"     https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
"
" Then open vim and run :PlugInstall

" Uncomment below to enable plugins
" call plug#begin('~/.vim/plugged')
"
" " Essential plugins
" Plug 'tpope/vim-sensible'           " Sensible defaults
" Plug 'tpope/vim-fugitive'           " Git integration
" Plug 'tpope/vim-commentary'         " Easy commenting (gc)
" Plug 'tpope/vim-surround'           " Manipulate surrounding chars
" Plug 'tpope/vim-repeat'             " Better repeat with .
"
" " File navigation
" Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
" Plug 'junegunn/fzf.vim'             " Fuzzy finder
" Plug 'preservim/nerdtree'           " File tree explorer
" Plug 'ryanoasis/vim-devicons'       " File icons (requires Nerd Font)
"
" " Code quality
" Plug 'dense-analysis/ale'           " Async linting
" Plug 'airblade/vim-gitgutter'       " Git diff in gutter
"
" " Status line
" Plug 'vim-airline/vim-airline'      " Better status line
" Plug 'vim-airline/vim-airline-themes'
"
" " Color schemes
" Plug 'morhetz/gruvbox'              " Gruvbox color scheme
" Plug 'joshdick/onedark.vim'         " Onedark color scheme
" Plug 'arcticicestudio/nord-vim'     " Nord color scheme
" Plug 'dracula/vim', { 'as': 'dracula' }  " Dracula color scheme
"
" call plug#end()

" ============================================================================
" Plugin Configuration
" ============================================================================

" FZF mappings (uncomment when plugin is installed)
" nnoremap <C-p> :Files<CR>
" nnoremap <leader>b :Buffers<CR>
" nnoremap <leader>f :Rg<CR>

" NERDTree mappings (uncomment when plugin is installed)
" nnoremap <leader>n :NERDTreeToggle<CR>
" nnoremap <leader>nf :NERDTreeFind<CR>

" ALE configuration (uncomment when plugin is installed)
" let g:ale_linters = {
" \   'javascript': ['eslint'],
" \   'python': ['flake8', 'pylint'],
" \   'go': ['gopls'],
" \}
" let g:ale_fixers = {
" \   '*': ['remove_trailing_lines', 'trim_whitespace'],
" \   'javascript': ['eslint'],
" \   'python': ['black', 'isort'],
" \}
" let g:ale_fix_on_save = 1

" Airline configuration (uncomment when plugin is installed)
" let g:airline#extensions#tabline#enabled = 1
" let g:airline_powerline_fonts = 1

" Color scheme (uncomment when plugin is installed)
" set termguicolors
" colorscheme gruvbox
" set background=dark
